name: Keith Loy
markdown: redcarpet
pygments: true
excerpt_separator: <!--more-->
linked_in: http://www.linkedin.com/pub/keith-loy/21/676/70
github: https://github.com/kloy
twitter: https://twitter.com/guynamedkeith